install:
	$(MAKE) -C settings
	$(MAKE) homebrew
	brew install bettertouchtool
	brew install goland
	brew install iterm2

homebrew:
	curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
