#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message. 
#

# current branch
NAME=$(git branch | grep '*' | sed 's/* //') 

# current branch description
DESCRIPTION=$(git config branch."$NAME".description) 

# commit message so far (often populated by a template)
TEXT="$(cat "$1")"

if [ -n "$TEXT" ]
then
	
	# Prepend # to ensure that branch name is a comment. This way, when the 
	# commit message is loaded, it counts as empty because all lines are empty
	# or are comments. This means that if the commit is cancelled without a 
	# message save, no commit is made.
    echo "#$NAME: \n$TEXT" > "$1"
    
    if [ -n "$DESCRIPTION" ] 
    then
       echo "" >> "$1"
       echo $DESCRIPTION >> "$1"
    fi

else

    echo "Error whilst applying prepare-commit-msg: $1 is empty"
    exit 1
    
fi