#!/bin/bash
parse-key-value(){
	keyValueFile="$1"
	key="$2"

	keyValue="$(look "$key" "$keyValueFile")"
	status="$?"
	if [[ ! $status = 0 ]]; then
		echo "could not find value for key: $key"
		exit $?
	fi

	value=${keyValue#$key} #what about when there are multiple entries?
	# If value's first character is an equals
	if [[ ${value:0:1} == "=" ]] ; then
		value=${value:1};
	else
		echo "Invalid key format: $key";
		exit 1;
	fi
	echo $value
	os="$(uname)"
	if [[ $os = 'Darwin' ]]; then
		echo $value | pbcopy
	elif [[ $os = 'Linux' ]]; then
		echo $value | xsel -ib
	else
		echo "Unable to copy url to clipboard."
		echo "OS: $os"
		exit
	fi
	echo "Copied to clipboard"
	# if looking for X, look may return all matching X, X***, etc.
}

awsConsoleSignInKVStore=${AWS_SIGNIN_KV}
if [[ ! -f "${AWS_SIGNIN_KV}" ]]; then
	echo "Can't find key value store at $AWS_SIGNIN_KV"
	exit 1
fi
account="$1"
if [[ -z $account ]]; then
	cat ${AWS_SIGNIN_KV}
	printf "\n"
	exit 1
fi
parse-key-value "${AWS_SIGNIN_KV}" "$account"