#!/bin/bash
# html-pdf
if [[ -z "$1" ]]; then
	echo "No file given."
	exit 1
fi
file="$1"
if [[ ! -f "$file" ]]; then
	echo "File does not exist: $file"
	exit 2
fi

fileBase="${file%.*}"
outFile="$fileBase.pdf"
wkhtmltopdf --dpi 325 -O portrait "$file" "$outFile"
if [[ "$2" = "--open" ]]; then 
	open -g $outFile
fi