#!/bin/bash
# md-html
if [[ -z "$1" ]]; then
	echo "No file given."
	return 1
fi
file="$1"
if [[ ! -f "$file" ]]; then
	echo "File does not exist: $file"
	return 2
fi
fileBase="${file%.*}"
outFile="$fileBase.html"
tmpFile="/tmp/$(basename $outFile.mid)"
markdown "$file" > "$tmpFile"
echo "[$(date +%Y-%m-%dT%H:%M:%S%z)] $file -> $outFile"
cat "$GOHBASHPROFILE_DIR/scripts/md.css.html" "$tmpFile" > "$outFile"
rm "$tmpFile"
if [[ "$2" = "--open" ]]; then 
	echo "opening $outFile"
	open -g "$outFile"
fi