#!/bin/bash
# md-pdf
if [[ -z "$1" ]]; then
	echo "No file given."
	exit 1
fi
file="$1"
if [[ ! -f "$file" ]]; then
	echo "File does not exist."
	exit 2
fi
md-html "$file"
fileBase="${file%.*}"
htmlFile="$fileBase.html"
html-pdf "$htmlFile"
if [[ "$2" = "--open" ]]; then 
	open -g $fileBase.pdf
fi