settings: appearance dock menubar

appearance:
	gsettings set org.gnome.desktop.interface text-scaling-factor 0.7
	gsettings set org.gnome.desktop.interface toolbar-icons-size "small"

dock:
	gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
	gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
	gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 12

menubar:
	gsettings set org.gnome.desktop.interface clock-show-date true
	gsettings set org.gnome.desktop.interface show-battery-percentage true
	gsettings set org.gnome.desktop.interface clock-show-weekday false
