#!/bin/bash
get-value(){
	local jsonFile="$1"
	local key="$2"

	jq -r .\"$key\" $jsonFile
}

copy-to-clipboard() {
	local value="$1"
	local os="$(uname)"

	if [[ $os = 'Darwin' ]]; then
		echo $value | pbcopy
	elif [[ $os = 'Linux' ]]; then
		echo $value | xsel -ib
	else
		echo "Unable to copy url to clipboard."
		echo "OS: $os"
		return 1
	fi
	echo "Copied to clipboard"
}

if [[ ! -f "${AWS_SIGNIN_URLS}" ]]; then
	echo "Can't find json store at $AWS_SIGNIN_URLS"
	exit 1
fi

account="$1"
if [[ -z $account ]]; then
	cat ${AWS_SIGNIN_URLS}
	printf "\n"
	exit 2
fi

value="$(get-value "${AWS_SIGNIN_URLS}" "$account")"
echo $value
copy-to-clipboard "$value"