#!/bin/bash
set -e
dateString="$(date -u "+20%y%m%d_%H%M%S")"
for d in $(go list ./... | grep -v vendor); do
    randomString="$(openssl rand -base64 32 | fold -w3 | head -n1)"
	coveragefile="/tmp/coverage$dateString-$randomString.out"
    go test "$d" $@ -coverprofile=$coveragefile && go tool cover -func=$coveragefile && go tool cover -html=$coveragefile
done