#!/bin/bash
if [[ -z "$1" ]]; then
	echo "No file given."
	exit 1
fi
file="$1"
if [[ ! -f "$file" ]]; then
	echo "File does not exist: $file"
	exit 2
fi

fileBase="${file%.*}"
outFile="$fileBase.html"

# If the second argument isn't --open but does contain information, it must be the outfile argument
if [[ ! "$2" = "--open" ]] && [[ -n "$2" ]]; then 
	outFile="$2"
fi

tmpFile="/tmp/$(basename $outFile.mid)"
markdown "$file" > "$tmpFile"
echo "[$(date +%Y-%m-%dT%H:%M:%S%z)] $file -> $outFile"
css="${GOH_BASHPROFILE_DIR:?GOH_BASHPROFILE_DIR must be set}/scripts/md.css.html"
if [[ ! -f "$css" ]]; then
	echo "css cannot be found at $css"
fi
( echo "<style type=\"text/css\">" && cat "$css" && echo "</style>" && cat "$tmpFile" ) > "$outFile"
rm "$tmpFile"

# If last argument is --open, open the file
if [[ "${!#}" = "--open" ]]; then 
	echo "opening $outFile"
	open -g "$outFile"
fi