#!/bin/bash
# md-pdf
if [[ -z "$1" ]]; then
	echo "No file given."
	exit 1
fi
file="$1"
if [[ ! -f "$file" ]]; then
	echo "File does not exist: $file"
	exit 2
fi

extension="${file##*.}"
if [[ ! $extension = md ]]; then
	echo "File doesn't have .md extension, has $extension"
	exit 3
fi

css=$GOH_BASHPROFILE_DIR/scripts/md.css
highlightcss=$GOH_BASHPROFILE_DIR/scripts/solarized-dark.css
baseName="$(basename $file)"
fileBase="${baseName%.*}"
docker run --rm \
	--user="$(id -u):$(id -g)" \
	-v "$file:$file" \
	-v "$PWD:$PWD" \
	-v "$css:$css" \
	-v "$highlightcss:$highlightcss" \
	auchida/markdown-pdf \
	markdown-pdf \
	-o "$PWD/$fileBase.pdf" \
	--css-path "$css" \
	--highlight-css-path $highlightcss \
	--paper-border 10mm \
	$file